blank_issues_enabled: false
contact_links:
  - name: GhostClient Support Server
    url: https://ghostclient.app/invite
    about: The best place to get immediate support.
  - name: Troubleshooting Guide
    url: https://docs.ghostclient.app/users/getting-started/troubleshooting
    about: The user troubleshooting guide from the documentation.